# Generated by Django 5.0.6 on 2024-06-17 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='content',
        ),
    ]
